source 'https://rubygems.org'
ruby "2.1.0", :engine => "rbx", :engine_version => "2.2.7"

gem 'puma'
gem 'json'
gem 'sinatra'
gem 'twitter'
gem 'typhoeus'
gem 'instagram'
gem 'feedzirra'
gem 'haml'
gem 'sass'
gem 'foreman'
gem 'tux'
gem 'tumblr_client'
